server:
  port: 8084
spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaker
          uri: https://github.com/SebastianLedesma/microservicios-tutorial
          search-paths: config-data
    application:
      name: config-service